import 'dart:io';
import 'dart:typed_data';
import 'dart:ui' as ui;

import 'package:flutter/services.dart' show rootBundle;
import 'package:flutter_test/flutter_test.dart';
import 'package:integration_test/integration_test.dart';
import 'package:monokit/monokit.dart';
import 'package:monolens/monolens.dart';
import 'package:monolens_example/capture_page.dart';
import 'package:monolens_example/ui/lens_chrome.dart';

/// Exercises the real native path on a device or simulator: no fakes, no mocked
/// channel. Everything here goes through AVFoundation on iOS and Media3
/// Transformer on Android.
///
/// The fixtures are generated by `swift tool/make_fixture.swift` — a 5 s
/// 640x360 clip with a keyframe every second (so a mid-GOP cut is genuinely
/// exercised) and an 800x600 still divided into coloured quadrants.
void main() {
  IntegrationTestWidgetsFlutterBinding.ensureInitialized();

  final MediaEditor editor = MonolensEditor();
  late String videoPath;
  late String imagePath;
  late String stickerPath;

  setUpAll(() async {
    videoPath = await _materialize('assets/fixture.mp4');
    imagePath = await _materialize('assets/fixture.jpg');
    stickerPath = await _materialize('assets/fixture_sticker.png');
  });

  group('probe', () {
    test('reports the still\'s display dimensions', () async {
      final info = await editor.probe(imagePath);
      expect(info.width, 800);
      expect(info.height, 600);
      expect(info.durationMs, isNull);
      expect(info.byteSize, greaterThan(0));
    });

    test('reports the clip\'s dimensions and duration', () async {
      final info = await editor.probe(videoPath);
      expect(info.width, 640);
      expect(info.height, 360);
      // Container duration lands within a frame of the nominal 5 s.
      expect(info.durationMs, closeTo(5000, 100));
    });
  });

  group('image edit', () {
    test('crops to the requested pixel region', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(
          crop: CropRect(left: 0, top: 0, width: 0.5, height: 0.5),
        ),
      );
      expect(result.width, 400);
      expect(result.height, 300);
      expect(File(result.path).existsSync(), isTrue);
      expect(result.origin, MediaOrigin.edit);
    });

    test('a quarter turn swaps the reported dimensions', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(rotation: MonoRotation.quarterTurn),
      );
      expect(result.width, 600);
      expect(result.height, 800);
    });

    test('crop, rotate and downscale compose in that order', () async {
      // Crop the left half (400x600), quarter-turn it (600x400), then cap the
      // longest edge at 300 → 300x200.
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(
          crop: CropRect(left: 0, top: 0, width: 0.5, height: 1),
          rotation: MonoRotation.quarterTurn,
          maxDimension: 300,
        ),
      );
      expect(result.width, 300);
      expect(result.height, 200);
    });

    test('writes png when asked', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(format: MonoImageFormat.png),
      );
      expect(result.contentType, 'image/png');
      expect(result.path, endsWith('.png'));
    });
  });

  // The fixture still is quartered — red top-left, green top-right, blue
  // bottom-left, yellow bottom-right — so the pixels prove *which* region
  // survived and which way up it came out. Dimensions alone would not: a
  // transform composed in the wrong order gets the size right and the picture
  // wrong, and that is exactly the bug worth catching across two platforms.
  group('image orientation', () {
    test('a crop keeps the region that was asked for', () async {
      final topLeft = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(
          crop: CropRect(left: 0, top: 0, width: 0.5, height: 0.5),
        ),
      );
      expect(await _sample(topLeft.path, 0.5, 0.5), _red);

      final bottomRight = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(
          crop: CropRect(left: 0.5, top: 0.5, width: 0.5, height: 0.5),
        ),
      );
      expect(await _sample(bottomRight.path, 0.5, 0.5), _yellow);
    });

    test('a quarter turn rotates clockwise', () async {
      // Clockwise, the bottom-left corner becomes the top-left one.
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(rotation: MonoRotation.quarterTurn),
      );
      expect(await _sample(result.path, 0.25, 0.25), _blue);
      expect(await _sample(result.path, 0.75, 0.25), _red);
    });

    test('a flip mirrors horizontally', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(flipHorizontal: true),
      );
      expect(await _sample(result.path, 0.25, 0.25), _green);
      expect(await _sample(result.path, 0.75, 0.25), _red);
    });

    test('a flip mirrors the rotated frame, not the source', () async {
      // The order the two compose in is the thing that silently differed
      // between the platforms before this test existed.
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(
          rotation: MonoRotation.quarterTurn,
          flipHorizontal: true,
        ),
      );
      expect(await _sample(result.path, 0.25, 0.25), _red);
      expect(await _sample(result.path, 0.75, 0.25), _blue);
    });

    test('downscaling does not disturb the orientation', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        const ImageEdit(rotation: MonoRotation.quarterTurn, maxDimension: 120),
      );
      expect(result.width, 90);
      expect(result.height, 120);
      expect(await _sample(result.path, 0.25, 0.25), _blue);
    });
  });

  group('annotations', () {
    test('a stroke is burned into the pixels', () async {
      // A thick green line straight across the middle of the frame.
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          annotations: [
            StrokeAnnotation(
              points: const [Offset(0.05, 0.5), Offset(0.95, 0.5)],
              colorArgb: 0xFF00FF00,
              widthFraction: 0.08,
            ),
          ],
        ),
      );
      // Dead centre is on the line; well above it is still the source's red.
      expect(await _sample(result.path, 0.5, 0.5), _green);
      expect(await _sample(result.path, 0.25, 0.15), _red);
    });

    test('a sticker is composited into its rect', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          annotations: [
            StickerAnnotation(
              imagePath: stickerPath,
              rect: const CropRect(
                left: 0.25,
                top: 0.25,
                width: 0.5,
                height: 0.5,
              ),
            ),
          ],
        ),
      );

      expect(await _magenta(result.path, 0.5, 0.5), isTrue);
      // Outside the rect the picture is untouched.
      expect(await _sample(result.path, 0.05, 0.05), _red);
      expect(await _sample(result.path, 0.95, 0.95), _yellow);
    });

    test('a sticker stretches to fill a non-square rect', () async {
      // Both platforms draw a sticker into its rect rather than fitting it
      // inside, so a square sticker in a wide rect reaches the rect's corners.
      // This is the semantic the editor's preview has to match — getting it
      // wrong shows up as a sticker that looks right until it is exported.
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          annotations: [
            StickerAnnotation(
              imagePath: stickerPath,
              rect: const CropRect(
                left: 0.1,
                top: 0.4,
                width: 0.8,
                height: 0.2,
              ),
            ),
          ],
        ),
      );

      // Just inside each end of the rect. Letterboxing would leave these as
      // the source's colours.
      expect(await _magenta(result.path, 0.13, 0.5), isTrue);
      expect(await _magenta(result.path, 0.87, 0.5), isTrue);
      // Just outside its top edge.
      expect(await _magenta(result.path, 0.5, 0.35), isFalse);
    });

    test('sticker opacity blends with the picture underneath', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          annotations: [
            StickerAnnotation(
              imagePath: stickerPath,
              rect: const CropRect(
                left: 0.05,
                top: 0.05,
                width: 0.35,
                height: 0.35,
              ),
              opacity: 0.5,
            ),
          ],
        ),
      );

      // Half magenta over red: red stays high, blue arrives but not fully.
      final (r, g, b) = await _channels(result.path, 0.2, 0.2);
      expect(r, greaterThan(150));
      expect(g, lessThan(90));
      expect(b, greaterThan(60));
      expect(b, lessThan(200), reason: 'a fully opaque sticker would be 255');
    });

    test('a blur region mixes the colours it straddles', () async {
      // Centred on the red/green seam, so a working blur produces a blend that
      // is neither. A no-op blur would leave a hard edge and pure colours.
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          annotations: [
            BlurAnnotation(
              rect: const CropRect(
                left: 0.35,
                top: 0.1,
                width: 0.3,
                height: 0.3,
              ),
              strength: 1,
            ),
          ],
        ),
      );
      // Assert on the channels, not the colour name: a 50/50 red-green blend
      // lands within a couple of units of the naming threshold, so which name
      // it rounds to is luck. That both channels are strongly present is the
      // actual claim — pure red has no green in it, and pure green no red.
      final (r, g, b) = await _channels(result.path, 0.5, 0.25);
      expect(r, greaterThan(40), reason: 'red bled into the seam');
      expect(g, greaterThan(40), reason: 'green bled into the seam');
      expect(b, lessThan(60), reason: 'nothing blue was nearby');

      // Outside the region the picture is untouched.
      expect(await _sample(result.path, 0.1, 0.25), _red);
    });

    test('text lands where it was placed', () async {
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          annotations: [
            TextAnnotation(
              text: 'MONOLENS',
              center: const Offset(0.5, 0.75),
              heightFraction: 0.2,
              colorArgb: 0xFFFFFFFF,
              // A solid plate behind the glyphs. Sampling a glyph directly
              // would be a coin flip on inter-letter gaps and on how each
              // platform's font stack shapes the string; the plate is exactly
              // where the annotation says it is on both.
              backgroundArgb: 0xFF000000,
            ),
          ],
        ),
      );
      final onPlate = await _sample(result.path, 0.5, 0.75);
      expect(onPlate, isNot(_blue));
      expect(onPlate, isNot(_yellow));
      // A corner far from the text is untouched.
      expect(await _sample(result.path, 0.05, 0.95), _blue);
    });

    test('annotations survive a crop, in output coordinates', () async {
      // Crop to the bottom-right (yellow) quadrant, then put a stroke across
      // the middle of *that* — annotations are placed against what the author
      // sees, not against the source.
      final result = await editor.applyImageEdit(
        imagePath,
        ImageEdit(
          crop: const CropRect(left: 0.5, top: 0.5, width: 0.5, height: 0.5),
          annotations: [
            StrokeAnnotation(
              points: const [Offset(0.05, 0.5), Offset(0.95, 0.5)],
              colorArgb: 0xFF00FF00,
              widthFraction: 0.1,
            ),
          ],
        ),
      );
      expect(result.width, 400);
      expect(result.height, 300);
      expect(await _sample(result.path, 0.5, 0.5), _green);
      expect(await _sample(result.path, 0.5, 0.1), _yellow);
    });
  });

  group('video annotations', () {
    /// Exports a short range and samples one decoded frame of the result.
    Future<(int, int, int)> exportAndSample(
      List<Annotation> annotations,
      double fx,
      double fy, {
      bool flip = false,
    }) async {
      final job = editor.startTrim(
        videoPath,
        VideoEdit(
          trim: const VideoTrim(
            start: Duration(milliseconds: 200),
            end: Duration(milliseconds: 700),
          ),
          flipHorizontal: flip,
          annotations: annotations,
        ),
      );
      final exported = await job.result;
      final frames = await editor.filmstrip(
        exported.path,
        duration: exported.duration,
        frames: 1,
        maxDimension: 640,
      );
      return _channelsOf(frames.single, fx, fy);
    }

    test(
      'a blur region changes the frame, and only inside the region',
      () async {
        // The fixture draws a hard-edged white block near the bottom-left of each
        // frame. A blur over it has something to smear; a blur over flat colour
        // would be indistinguishable from doing nothing, which is exactly the
        // failure this test has to be able to see.
        final region = BlurAnnotation(
          rect: const CropRect(left: 0, top: 0.75, width: 0.2, height: 0.25),
          strength: 1,
        );
        // The control also blurs, just somewhere else. An export with no
        // annotations at all takes a different pipeline — on iOS it skips the
        // video composition entirely — so comparing against one would measure
        // the gap between two encoders rather than the effect of the blur.
        final elsewhere = BlurAnnotation(
          rect: const CropRect(left: 0.6, top: 0, width: 0.2, height: 0.2),
          strength: 1,
        );

        // The fixture draws a hard-edged white block near the bottom-left of
        // each frame; this samples just inside its edge. A blur over flat
        // colour would be indistinguishable from doing nothing, which is
        // exactly the failure this test has to be able to see.
        const insideX = 0.105;
        const insideY = 0.87;
        final withoutBlur = await exportAndSample(
          [elsewhere],
          insideX,
          insideY,
        );
        final withBlur = await exportAndSample([region], insideX, insideY);

        final changed =
            (withoutBlur.$1 - withBlur.$1).abs() +
            (withoutBlur.$2 - withBlur.$2).abs() +
            (withoutBlur.$3 - withBlur.$3).abs();
        expect(
          changed,
          greaterThan(30),
          reason: 'the blur should visibly alter pixels inside its region',
        );

        // A point outside both regions. This is the half of the claim that
        // separates a masked blur from a whole-frame one: if either platform
        // ignored its mask, this would move too.
        const outsideX = 0.4;
        const outsideY = 0.5;
        final controlOutside = await exportAndSample(
          [elsewhere],
          outsideX,
          outsideY,
        );
        final targetOutside = await exportAndSample(
          [region],
          outsideX,
          outsideY,
        );

        final untouched =
            (controlOutside.$1 - targetOutside.$1).abs() +
            (controlOutside.$2 - targetOutside.$2).abs() +
            (controlOutside.$3 - targetOutside.$3).abs();
        expect(
          untouched,
          lessThan(36),
          reason: 'outside every region only re-encoding noise should differ',
        );
      },
      timeout: const Timeout(Duration(minutes: 3)),
    );

    test('a flip mirrors the frame', () async {
      // The fixture draws its white counter block near the *left* edge. Mirror
      // the frame and it has to appear near the right, with the left falling
      // back to the underlying gradient — an assertion a no-op flip fails and
      // a whole-frame colour shift cannot fake.
      final plain = await exportAndSample(const [], 0.09, 0.87);
      final sameSpot = await exportAndSample(const [], 0.09, 0.87, flip: true);
      final otherSide = await exportAndSample(const [], 0.91, 0.87, flip: true);

      // The block is bright; the gradient behind it is not.
      int luma((int, int, int) c) => c.$1 + c.$2 + c.$3;

      expect(
        luma(plain),
        greaterThan(luma(sameSpot) + 90),
        reason: 'the block should have left the spot it started in',
      );
      expect(
        luma(otherSide),
        greaterThan(luma(sameSpot) + 90),
        reason: 'and arrived on the opposite side',
      );
    }, timeout: const Timeout(Duration(minutes: 3)));

    test(
      'an overlay is burned into every frame',
      () async {
        final sampled = await exportAndSample(
          [
            StrokeAnnotation(
              points: const [Offset(0.05, 0.5), Offset(0.95, 0.5)],
              colorArgb: 0xFF00FF00,
              widthFraction: 0.15,
            ),
          ],
          0.5,
          0.5,
        );

        // Strongly green, whatever the underlying gradient was doing.
        expect(sampled.$2, greaterThan(150));
        expect(sampled.$1, lessThan(150));
      },
      timeout: const Timeout(Duration(minutes: 3)),
    );
  });

  group('video trim', () {
    test('cuts mid-GOP to the requested range', () async {
      // 1.5 s is deliberately not on a keyframe: a passthrough export would
      // slide this back to 1.0 s.
      final job = editor.startTrim(
        videoPath,
        const VideoEdit(
          trim: VideoTrim(
            start: Duration(milliseconds: 1500),
            end: Duration(milliseconds: 3500),
          ),
        ),
      );

      final ticks = <double>[];
      job.progress.listen(ticks.add);

      final result = await job.result;
      expect(result.duration.inMilliseconds, closeTo(2000, 120));
      expect(result.width, 640);
      expect(result.height, 360);
      expect(File(result.path).existsSync(), isTrue);
      expect(result.byteSize, greaterThan(0));

      // The exported file must itself measure ~2 s, not just be reported as it.
      final reprobed = await editor.probe(result.path);
      expect(reprobed.durationMs, closeTo(2000, 200));

      expect(ticks, isNotEmpty, reason: 'export should report progress');
      expect(ticks.last, lessThanOrEqualTo(1.0));
    });

    test('muting drops the audio track', () async {
      final job = editor.startTrim(
        videoPath,
        const VideoEdit(
          trim: VideoTrim(
            start: Duration.zero,
            end: Duration(milliseconds: 2000),
          ),
          muteAudio: true,
        ),
      );
      final result = await job.result;
      expect(File(result.path).existsSync(), isTrue);
      expect(result.duration.inMilliseconds, closeTo(2000, 120));
    });

    test('cancel settles the job rather than hanging it', () async {
      final job = editor.startTrim(
        videoPath,
        const VideoEdit(
          trim: VideoTrim(start: Duration.zero, end: Duration(seconds: 5)),
        ),
      );
      // Cancel immediately: this races the export's own start, which is the
      // case the platform code has an explicit pre-start guard for.
      await job.cancel();
      await expectLater(job.result, throwsA(isA<TrimCancelled>()));
    });

    test('an empty range is refused rather than exported', () async {
      final job = editor.startTrim(
        videoPath,
        const VideoEdit(
          trim: VideoTrim(
            start: Duration(milliseconds: 2000),
            end: Duration(milliseconds: 2000),
          ),
        ),
      );
      await expectLater(job.result, throwsA(isA<MediaEditException>()));
    });
  });

  // Runs wherever a camera actually exists — an Android emulator with a
  // virtual scene, or a real handset. Skips on the iOS simulator, which has no
  // camera to open.
  group('camera', () {
    // Opening the device is the slow part — on an emulator's virtual scene it
    // can take over two minutes — so each mode is opened once and everything
    // that mode can prove is asserted against it. The generous timeout is for
    // that cold start; on a handset the whole group runs in seconds.
    const cameraTimeout = Timeout(Duration(minutes: 5));

    late MonolensCameraSession session;

    setUp(() => session = MonolensCameraSession());
    tearDown(() => session.dispose());

    test(
      'previews and captures a still that round-trips through the editor',
      () async {
        if (await session.initialize(CameraCaptureMode.photo) !=
            CameraAccess.granted) {
          markTestSkipped('no camera on this device');
          return;
        }
        expect(session.isInitialized, isTrue);

        // The headless contract: an id the host hands to a Texture widget, plus
        // enough geometry to orient it. No widget crosses this boundary.
        final preview = session.preview;
        expect(preview, isNotNull);
        expect(preview!.textureId, greaterThanOrEqualTo(0));
        expect(preview.size.width, greaterThan(0));
        expect(preview.size.height, greaterThan(0));
        expect(preview.aspectRatio, greaterThan(0));

        final photo = await session.capturePhoto();
        expect(File(photo.path).existsSync(), isTrue);
        expect(photo.origin, MediaOrigin.camera);
        expect(photo.width, greaterThan(0));
        expect(photo.byteSize, greaterThan(0));

        // Capture feeding straight into edit is the reason the two live in one
        // package rather than two.
        final cropped = await editor.applyImageEdit(
          photo.path,
          const ImageEdit(
            crop: CropRect(left: 0.25, top: 0.25, width: 0.5, height: 0.5),
          ),
        );
        expect(cropped.width, closeTo(photo.width / 2, 2));
        expect(cropped.height, closeTo(photo.height / 2, 2));
      },
      timeout: cameraTimeout,
    );

    test('a recording auto-stops at the cap', () async {
      if (await session.initialize(CameraCaptureMode.video) !=
          CameraAccess.granted) {
        markTestSkipped('no camera on this device');
        return;
      }

      await session.startVideoRecording(
        maxDuration: const Duration(seconds: 2),
      );
      expect(session.isRecording.value, isTrue);

      // The session clears the flag itself — no second shutter tap — which is
      // what lets a capped composer never have to reject its own take.
      final deadline = DateTime.now().add(const Duration(seconds: 20));
      while (session.isRecording.value && DateTime.now().isBefore(deadline)) {
        await Future<void>.delayed(const Duration(milliseconds: 100));
      }
      expect(
        session.isRecording.value,
        isFalse,
        reason: 'the cap should stop the take without the caller asking',
      );
      expect(session.recordedDuration.value.inMilliseconds, closeTo(2000, 400));

      final clip = await session.stopVideoRecording();
      expect(File(clip.path).existsSync(), isTrue);
      expect(clip.origin, MediaOrigin.camera);
      // Encoders round to whole frames, so allow a generous window.
      expect(clip.duration.inMilliseconds, greaterThan(1000));
      expect(clip.duration.inMilliseconds, lessThan(4000));
    }, timeout: cameraTimeout);
  });

  // The example's own capture chrome, pumped against the real camera.
  //
  // The group above proves the *plugin* can open a device and produce a file.
  // This one proves the shutter, the countdown and the auto-collect wired
  // around it behave -- which is host code, and the part a reader of this
  // example is most likely to copy. Only a device with a lens can run it.
  group('capture chrome', () {
    const chromeTimeout = Timeout(Duration(minutes: 5));

    /// Pushes [CapturePage] onto a real navigator and returns what it pops.
    ///
    /// The page reports its result by popping, so a harness has to be the
    /// thing that receives it -- pumping the page bare would leave nowhere for
    /// the captured media to go.
    Future<CapturedMedia?> harness(
      WidgetTester tester,
      CameraCaptureMode mode, {
      Duration maxDuration = const Duration(seconds: 15),
    }) async {
      CapturedMedia? result;
      var popped = false;

      await tester.pumpWidget(
        MonokitApp(
          theme: MonokitThemeData.dark(),
          home: Builder(
            builder: (context) => MonoScreen(
              body: Center(
                child: MonoButton(
                  onPressed: () async {
                    result = await Navigator.of(context).push<CapturedMedia>(
                      LensRoute<CapturedMedia>(
                        builder: (_) =>
                            CapturePage(mode: mode, maxDuration: maxDuration),
                      ),
                    );
                    popped = true;
                  },
                  child: const Text('open'),
                ),
              ),
            ),
          ),
        ),
      );

      await tester.tap(find.text('open'));
      // Pumped, not settled: the page shows a spinner until the device opens,
      // and pumpAndSettle waits for animations to stop -- which a spinner
      // never does.
      for (var i = 0; i < 6; i++) {
        await tester.pump(const Duration(milliseconds: 100));
      }

      // Opening the device is asynchronous and slow; the viewfinder only
      // appears once the session reports back.
      final deadline = DateTime.now().add(const Duration(minutes: 2));
      while (find.byType(Texture).evaluate().isEmpty &&
          DateTime.now().isBefore(deadline)) {
        await tester.pump(const Duration(milliseconds: 200));
      }
      if (find.byType(Texture).evaluate().isEmpty) return null;

      // The headless contract, reaching the screen: the preview is a plain
      // Texture this app built, not a widget the plugin handed over.
      expect(find.byType(Texture), findsOneWidget);

      if (mode == CameraCaptureMode.photo) {
        expect(find.text('PHOTO'), findsOneWidget);
      } else {
        expect(find.text('VIDEO'), findsOneWidget);
      }

      await tester.tap(find.byType(LensShutter));

      if (mode == CameraCaptureMode.video) {
        await tester.pump(const Duration(milliseconds: 300));
        // The take is live: the mode pill gives way to the countdown, and the
        // shutter now offers to stop rather than to start.
        expect(find.text('VIDEO'), findsNothing);
        // Asserted on the widget rather than on its semantic label, so the
        // test does not depend on the semantics tree being built.
        expect(
          tester.widget<LensShutter>(find.byType(LensShutter)).isRecording,
          isTrue,
        );
      }

      // Then wait for the page to hand its result back. For video this covers
      // the whole cap, since nothing taps the shutter a second time.
      final settle = DateTime.now().add(const Duration(seconds: 45));
      while (!popped && DateTime.now().isBefore(settle)) {
        await tester.pump(const Duration(milliseconds: 200));
      }
      expect(popped, isTrue, reason: 'the page never popped its result');
      return result;
    }

    testWidgets('the shutter captures a still and hands it back', (
      tester,
    ) async {
      final probe = MonolensCameraSession();
      final access = await probe.initialize(CameraCaptureMode.photo);
      await probe.dispose();
      if (access != CameraAccess.granted) {
        markTestSkipped('no camera on this device');
        return;
      }

      final photo = await harness(tester, CameraCaptureMode.photo);
      expect(photo, isNotNull);
      expect(File(photo!.path).existsSync(), isTrue);
      expect(photo.origin, MediaOrigin.camera);
      expect(photo.width, greaterThan(0));
      expect(photo.height, greaterThan(0));
    }, timeout: chromeTimeout);

    testWidgets('the cap collects the clip without a second tap', (
      tester,
    ) async {
      final probe = MonolensCameraSession();
      final access = await probe.initialize(CameraCaptureMode.video);
      await probe.dispose();
      if (access != CameraAccess.granted) {
        markTestSkipped('no camera on this device');
        return;
      }

      // The page pops on its own when the session clears the recording flag.
      // Nothing in this test stops the take -- that is the whole assertion.
      final clip = await harness(
        tester,
        CameraCaptureMode.video,
        maxDuration: const Duration(seconds: 3),
      );
      expect(clip, isNotNull);
      expect(File(clip!.path).existsSync(), isTrue);
      expect(clip, isA<CapturedVideo>());
      expect(
        (clip as CapturedVideo).duration.inMilliseconds,
        greaterThan(1000),
      );
      expect(clip.duration.inMilliseconds, lessThan(6000));
    }, timeout: chromeTimeout);
  });

  group('filmstrip', () {
    test('returns one decodable frame per requested timestamp', () async {
      final frames = await editor.filmstrip(
        videoPath,
        duration: const Duration(seconds: 5),
        frames: 6,
      );
      expect(frames, hasLength(6));
      for (final frame in frames) {
        expect(frame, isNotEmpty);
        // JPEG SOI marker — proof these are really encoded images.
        expect(frame[0], 0xFF);
        expect(frame[1], 0xD8);
      }
    });
  });
}

/// The fixture's four quadrant colours, as the nearest-name buckets [_sample]
/// reports. Exact RGB would be brittle — JPEG shifts every value a little.
const String _red = 'red';
const String _green = 'green';
const String _blue = 'blue';
const String _yellow = 'yellow';

/// Decodes [path] and names the colour at the given fractional position.
Future<String> _sample(String path, double fx, double fy) async {
  final (r, g, b) = await _channels(path, fx, fy);
  const threshold = 128;
  return switch ((r > threshold, g > threshold, b > threshold)) {
    (true, false, false) => _red,
    (false, true, false) => _green,
    (false, false, true) => _blue,
    (true, true, false) => _yellow,
    _ => 'rgb($r,$g,$b)',
  };
}

/// The raw channels at a fractional position of a file on disk.
Future<(int, int, int)> _channels(String path, double fx, double fy) async =>
    _channelsOf(await File(path).readAsBytes(), fx, fy);

/// The raw channels at a fractional position of encoded bytes — which is how a
/// filmstrip frame arrives, and therefore how a video export is inspected.
Future<(int, int, int)> _channelsOf(
  Uint8List bytes,
  double fx,
  double fy,
) async {
  final codec = await ui.instantiateImageCodec(bytes);
  final image = (await codec.getNextFrame()).image;
  final data = await image.toByteData(format: ui.ImageByteFormat.rawRgba);
  final x = (fx * image.width).clamp(0, image.width - 1).toInt();
  final y = (fy * image.height).clamp(0, image.height - 1).toInt();
  final offset = (y * image.width + x) * 4;

  final r = data!.getUint8(offset);
  final g = data.getUint8(offset + 1);
  final b = data.getUint8(offset + 2);
  image.dispose();
  return (r, g, b);
}

/// True when the pixel is the sticker's magenta. Named rather than compared to
/// an exact triple because the still is a JPEG and every channel moves a little.
Future<bool> _magenta(String path, double fx, double fy) async {
  final (r, g, b) = await _channels(path, fx, fy);
  return r > 180 && g < 90 && b > 180;
}

/// Copies a bundled asset onto disk, since every native op works on file paths.
Future<String> _materialize(String asset) async {
  final directory = await MonolensPlatform.instance.cacheDirectory();
  final file = File('$directory/${asset.split('/').last}');
  await file.writeAsBytes(
    (await rootBundle.load(asset)).buffer.asUint8List(),
    flush: true,
  );
  return file.path;
}
