// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Clockwise quarter turns applied after cropping.
enum MonoRotation {
  none,
  quarterTurn,
  halfTurn,
  threeQuarterTurns,
}

/// How a still is re-encoded on export.
enum MonoImageFormat {
  jpeg,
  png,
}

/// Which kind of overlay an [AnnotationSpec] describes.
enum AnnotationKind {
  text,
  sticker,
  blur,
  stroke,
}

enum BlurShapeSpec {
  rectangle,
  oval,
}

/// A crop as fractions of the frame, 0–1.
///
/// Normalized all the way to the platform rather than resolved to pixels in
/// Dart. That removes a probe round trip per edit — the native side is opening
/// the file anyway and already knows its dimensions — and it removes the chance
/// of the two sides disagreeing about what those dimensions are.
class NormalizedRect {
  NormalizedRect({
    required this.left,
    required this.top,
    required this.width,
    required this.height,
  });

  double left;

  double top;

  double width;

  double height;

  List<Object?> _toList() {
    return <Object?>[
      left,
      top,
      width,
      height,
    ];
  }

  Object encode() {
    return _toList();  }

  static NormalizedRect decode(Object result) {
    result as List<Object?>;
    return NormalizedRect(
      left: result[0]! as double,
      top: result[1]! as double,
      width: result[2]! as double,
      height: result[3]! as double,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! NormalizedRect || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(left, other.left) && _deepEquals(top, other.top) && _deepEquals(width, other.width) && _deepEquals(height, other.height);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'NormalizedRect(left: $left, top: $top, width: $width, height: $height)';
  }
}

class ImageEditRequest {
  ImageEditRequest({
    required this.sourcePath,
    required this.outputPath,
    this.crop,
    required this.rotation,
    required this.flipHorizontal,
    required this.format,
    required this.quality,
    this.maxDimension,
    required this.annotations,
  });

  String sourcePath;

  String outputPath;

  /// Null crops nothing — the full frame is re-encoded.
  NormalizedRect? crop;

  MonoRotation rotation;

  bool flipHorizontal;

  MonoImageFormat format;

  /// 1–100. Ignored for [MonoImageFormat.png].
  int quality;

  /// Downscales so the longest edge is at most this many pixels. Null keeps the
  /// cropped size. Applied after crop and rotation.
  int? maxDimension;

  /// Painted over the result, back to front, after every transform.
  List<AnnotationSpec> annotations;

  List<Object?> _toList() {
    return <Object?>[
      sourcePath,
      outputPath,
      crop,
      rotation,
      flipHorizontal,
      format,
      quality,
      maxDimension,
      annotations,
    ];
  }

  Object encode() {
    return _toList();  }

  static ImageEditRequest decode(Object result) {
    result as List<Object?>;
    return ImageEditRequest(
      sourcePath: result[0]! as String,
      outputPath: result[1]! as String,
      crop: result[2] as NormalizedRect?,
      rotation: result[3]! as MonoRotation,
      flipHorizontal: result[4]! as bool,
      format: result[5]! as MonoImageFormat,
      quality: result[6]! as int,
      maxDimension: result[7] as int?,
      annotations: (result[8]! as List<Object?>).cast<AnnotationSpec>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ImageEditRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourcePath, other.sourcePath) && _deepEquals(outputPath, other.outputPath) && _deepEquals(crop, other.crop) && _deepEquals(rotation, other.rotation) && _deepEquals(flipHorizontal, other.flipHorizontal) && _deepEquals(format, other.format) && _deepEquals(quality, other.quality) && _deepEquals(maxDimension, other.maxDimension) && _deepEquals(annotations, other.annotations);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ImageEditRequest(sourcePath: $sourcePath, outputPath: $outputPath, crop: $crop, rotation: $rotation, flipHorizontal: $flipHorizontal, format: $format, quality: $quality, maxDimension: $maxDimension, annotations: $annotations)';
  }
}

/// One annotation, flattened.
///
/// Deliberately a single struct with nullable fields rather than a sealed
/// hierarchy: the wire crosses three languages, and a flat record with a kind
/// tag is trivial for each native side to switch on. Dart keeps the sealed,
/// typed version and converts here, so only this one struct is ugly.
///
/// All geometry is normalized against the *output* frame — after crop and
/// rotation — because that is the frame the author placed it against.
class AnnotationSpec {
  AnnotationSpec({
    required this.kind,
    required this.rotation,
    this.text,
    this.centerX,
    this.centerY,
    this.heightFraction,
    this.colorArgb,
    this.backgroundArgb,
    this.imagePath,
    this.rect,
    this.opacity,
    this.strength,
    this.shape,
    this.points,
    this.widthFraction,
  });

  AnnotationKind kind;

  /// Clockwise radians. Applies to text and stickers.
  double rotation;

  String? text;

  double? centerX;

  double? centerY;

  /// Cap height as a fraction of the output's height.
  double? heightFraction;

  int? colorArgb;

  int? backgroundArgb;

  String? imagePath;

  NormalizedRect? rect;

  double? opacity;

  double? strength;

  BlurShapeSpec? shape;

  /// Stroke points, flattened as x, y, x, y — a flat list survives every
  /// codec without a nested type.
  List<double>? points;

  /// Stroke width as a fraction of the output's shorter edge.
  double? widthFraction;

  List<Object?> _toList() {
    return <Object?>[
      kind,
      rotation,
      text,
      centerX,
      centerY,
      heightFraction,
      colorArgb,
      backgroundArgb,
      imagePath,
      rect,
      opacity,
      strength,
      shape,
      points,
      widthFraction,
    ];
  }

  Object encode() {
    return _toList();  }

  static AnnotationSpec decode(Object result) {
    result as List<Object?>;
    return AnnotationSpec(
      kind: result[0]! as AnnotationKind,
      rotation: result[1]! as double,
      text: result[2] as String?,
      centerX: result[3] as double?,
      centerY: result[4] as double?,
      heightFraction: result[5] as double?,
      colorArgb: result[6] as int?,
      backgroundArgb: result[7] as int?,
      imagePath: result[8] as String?,
      rect: result[9] as NormalizedRect?,
      opacity: result[10] as double?,
      strength: result[11] as double?,
      shape: result[12] as BlurShapeSpec?,
      points: (result[13] as List<Object?>?)?.cast<double>(),
      widthFraction: result[14] as double?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! AnnotationSpec || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(kind, other.kind) && _deepEquals(rotation, other.rotation) && _deepEquals(text, other.text) && _deepEquals(centerX, other.centerX) && _deepEquals(centerY, other.centerY) && _deepEquals(heightFraction, other.heightFraction) && _deepEquals(colorArgb, other.colorArgb) && _deepEquals(backgroundArgb, other.backgroundArgb) && _deepEquals(imagePath, other.imagePath) && _deepEquals(rect, other.rect) && _deepEquals(opacity, other.opacity) && _deepEquals(strength, other.strength) && _deepEquals(shape, other.shape) && _deepEquals(points, other.points) && _deepEquals(widthFraction, other.widthFraction);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'AnnotationSpec(kind: $kind, rotation: $rotation, text: $text, centerX: $centerX, centerY: $centerY, heightFraction: $heightFraction, colorArgb: $colorArgb, backgroundArgb: $backgroundArgb, imagePath: $imagePath, rect: $rect, opacity: $opacity, strength: $strength, shape: $shape, points: $points, widthFraction: $widthFraction)';
  }
}

class VideoTrimRequest {
  VideoTrimRequest({
    required this.sourcePath,
    required this.outputPath,
    required this.startMs,
    required this.endMs,
    required this.muteAudio,
    this.crop,
    required this.rotation,
    required this.flipHorizontal,
    required this.annotations,
  });

  String sourcePath;

  String outputPath;

  int startMs;

  int endMs;

  /// Drops the audio track entirely rather than exporting a silent one.
  bool muteAudio;

  /// Null crops nothing.
  NormalizedRect? crop;

  MonoRotation rotation;

  /// Mirrors the *rotated* frame, matching the still path exactly.
  bool flipHorizontal;

  /// Burned into every frame, back to front.
  List<AnnotationSpec> annotations;

  List<Object?> _toList() {
    return <Object?>[
      sourcePath,
      outputPath,
      startMs,
      endMs,
      muteAudio,
      crop,
      rotation,
      flipHorizontal,
      annotations,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoTrimRequest decode(Object result) {
    result as List<Object?>;
    return VideoTrimRequest(
      sourcePath: result[0]! as String,
      outputPath: result[1]! as String,
      startMs: result[2]! as int,
      endMs: result[3]! as int,
      muteAudio: result[4]! as bool,
      crop: result[5] as NormalizedRect?,
      rotation: result[6]! as MonoRotation,
      flipHorizontal: result[7]! as bool,
      annotations: (result[8]! as List<Object?>).cast<AnnotationSpec>(),
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoTrimRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sourcePath, other.sourcePath) && _deepEquals(outputPath, other.outputPath) && _deepEquals(startMs, other.startMs) && _deepEquals(endMs, other.endMs) && _deepEquals(muteAudio, other.muteAudio) && _deepEquals(crop, other.crop) && _deepEquals(rotation, other.rotation) && _deepEquals(flipHorizontal, other.flipHorizontal) && _deepEquals(annotations, other.annotations);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoTrimRequest(sourcePath: $sourcePath, outputPath: $outputPath, startMs: $startMs, endMs: $endMs, muteAudio: $muteAudio, crop: $crop, rotation: $rotation, flipHorizontal: $flipHorizontal, annotations: $annotations)';
  }
}

/// What a probe or an export reports back about a file on disk.
class MediaInfo {
  MediaInfo({
    required this.path,
    required this.width,
    required this.height,
    this.durationMs,
    required this.byteSize,
  });

  String path;

  /// Display dimensions — already rotation-corrected, so a portrait clip
  /// recorded on a sensor-landscape device reports portrait here.
  int width;

  int height;

  /// Null for stills.
  int? durationMs;

  int byteSize;

  List<Object?> _toList() {
    return <Object?>[
      path,
      width,
      height,
      durationMs,
      byteSize,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaInfo decode(Object result) {
    result as List<Object?>;
    return MediaInfo(
      path: result[0]! as String,
      width: result[1]! as int,
      height: result[2]! as int,
      durationMs: result[3] as int?,
      byteSize: result[4]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaInfo || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(path, other.path) && _deepEquals(width, other.width) && _deepEquals(height, other.height) && _deepEquals(durationMs, other.durationMs) && _deepEquals(byteSize, other.byteSize);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaInfo(path: $path, width: $width, height: $height, durationMs: $durationMs, byteSize: $byteSize)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is MonoRotation) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is MonoImageFormat) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is AnnotationKind) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is BlurShapeSpec) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is NormalizedRect) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is ImageEditRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is AnnotationSpec) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is VideoTrimRequest) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is MediaInfo) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : MonoRotation.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : MonoImageFormat.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : AnnotationKind.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : BlurShapeSpec.values[value];
      case 133:
        return NormalizedRect.decode(readValue(buffer)!);
      case 134:
        return ImageEditRequest.decode(readValue(buffer)!);
      case 135:
        return AnnotationSpec.decode(readValue(buffer)!);
      case 136:
        return VideoTrimRequest.decode(readValue(buffer)!);
      case 137:
        return MediaInfo.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class MonolensHostApi {
  /// Constructor for [MonolensHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  MonolensHostApi({BinaryMessenger? binaryMessenger, String messageChannelSuffix = ''})
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
  final BinaryMessenger? pigeonVar_binaryMessenger;

  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;

  /// The app's cache directory, where exports are written.
  ///
  /// Asked of the platform rather than taken from `path_provider`, so the
  /// plugin carries no dependency for one string the native side already knows
  /// (`NSTemporaryDirectory()` / `context.cacheDir`). Contents are the OS's to
  /// evict — a caller keeping an export must copy it somewhere durable.
  Future<String> cacheDirectory() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.monolens.MonolensHostApi.cacheDirectory$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  /// Reads dimensions, duration and size without decoding the whole file.
  Future<MediaInfo> probe(String path) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.monolens.MonolensHostApi.probe$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaInfo;
  }

  Future<MediaInfo> editImage(ImageEditRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.monolens.MonolensHostApi.editImage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaInfo;
  }

  /// Re-encodes [request]'s range to a new file. [jobId] addresses the export
  /// for [cancel] and for progress delivered over [MonolensFlutterApi].
  Future<MediaInfo> trimVideo(VideoTrimRequest request, String jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.monolens.MonolensHostApi.trimVideo$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request, jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MediaInfo;
  }

  /// Requests cancellation of an in-flight [trimVideo]. A cancelled export
  /// completes with a `monolens/cancelled` error rather than a result.
  Future<void> cancel(String jobId) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.monolens.MonolensHostApi.cancel$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[jobId]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  /// Decodes frames at [atMs] for the trim filmstrip, each scaled so its
  /// longest edge is at most [maxDimension]. Returned as encoded JPEG bytes in
  /// the same order as the requested timestamps.
  Future<List<Uint8List>> videoThumbnails(String path, List<int> atMs, int maxDimension) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.monolens.MonolensHostApi.videoThumbnails$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[path, atMs, maxDimension]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<Uint8List>();
  }
}

abstract class MonolensFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  /// Fractional export progress in 0.0–1.0 for the job identified by [jobId].
  void onProgress(String jobId, double progress);

  static void setUp(MonolensFlutterApi? api, {BinaryMessenger? binaryMessenger, String messageChannelSuffix = '',}) {
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.monolens.MonolensFlutterApi.onProgress$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final String arg_jobId = args[0]! as String;
          final double arg_progress = args[1]! as double;
          try {
            api.onProgress(arg_jobId, arg_progress);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
