// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.monorithm.monolens

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
private object MessagesPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Clockwise quarter turns applied after cropping. */
enum class MonoRotation(val raw: Int) {
  NONE(0),
  QUARTER_TURN(1),
  HALF_TURN(2),
  THREE_QUARTER_TURNS(3);

  companion object {
    fun ofRaw(raw: Int): MonoRotation? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** How a still is re-encoded on export. */
enum class MonoImageFormat(val raw: Int) {
  JPEG(0),
  PNG(1);

  companion object {
    fun ofRaw(raw: Int): MonoImageFormat? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Which kind of overlay an [AnnotationSpec] describes. */
enum class AnnotationKind(val raw: Int) {
  TEXT(0),
  STICKER(1),
  BLUR(2),
  STROKE(3);

  companion object {
    fun ofRaw(raw: Int): AnnotationKind? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class BlurShapeSpec(val raw: Int) {
  RECTANGLE(0),
  OVAL(1);

  companion object {
    fun ofRaw(raw: Int): BlurShapeSpec? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/**
 * A crop as fractions of the frame, 0–1.
 *
 * Normalized all the way to the platform rather than resolved to pixels in
 * Dart. That removes a probe round trip per edit — the native side is opening
 * the file anyway and already knows its dimensions — and it removes the chance
 * of the two sides disagreeing about what those dimensions are.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class NormalizedRect (
  val left: Double,
  val top: Double,
  val width: Double,
  val height: Double
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): NormalizedRect {
      val left = pigeonVar_list[0] as Double
      val top = pigeonVar_list[1] as Double
      val width = pigeonVar_list[2] as Double
      val height = pigeonVar_list[3] as Double
      return NormalizedRect(left, top, width, height)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      left,
      top,
      width,
      height,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as NormalizedRect
    return MessagesPigeonUtils.deepEquals(this.left, other.left) && MessagesPigeonUtils.deepEquals(this.top, other.top) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.left)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.top)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    return result
  }
  override fun toString(): String {
    return "NormalizedRect(left=$left, top=$top, width=$width, height=$height)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ImageEditRequest (
  val sourcePath: String,
  val outputPath: String,
  /** Null crops nothing — the full frame is re-encoded. */
  val crop: NormalizedRect? = null,
  val rotation: MonoRotation,
  val flipHorizontal: Boolean,
  val format: MonoImageFormat,
  /** 1–100. Ignored for [MonoImageFormat.png]. */
  val quality: Long,
  /**
   * Downscales so the longest edge is at most this many pixels. Null keeps the
   * cropped size. Applied after crop and rotation.
   */
  val maxDimension: Long? = null,
  /** Painted over the result, back to front, after every transform. */
  val annotations: List<AnnotationSpec>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ImageEditRequest {
      val sourcePath = pigeonVar_list[0] as String
      val outputPath = pigeonVar_list[1] as String
      val crop = pigeonVar_list[2] as NormalizedRect?
      val rotation = pigeonVar_list[3] as MonoRotation
      val flipHorizontal = pigeonVar_list[4] as Boolean
      val format = pigeonVar_list[5] as MonoImageFormat
      val quality = pigeonVar_list[6] as Long
      val maxDimension = pigeonVar_list[7] as Long?
      val annotations = pigeonVar_list[8] as List<AnnotationSpec>
      return ImageEditRequest(sourcePath, outputPath, crop, rotation, flipHorizontal, format, quality, maxDimension, annotations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourcePath,
      outputPath,
      crop,
      rotation,
      flipHorizontal,
      format,
      quality,
      maxDimension,
      annotations,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ImageEditRequest
    return MessagesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.crop, other.crop) && MessagesPigeonUtils.deepEquals(this.rotation, other.rotation) && MessagesPigeonUtils.deepEquals(this.flipHorizontal, other.flipHorizontal) && MessagesPigeonUtils.deepEquals(this.format, other.format) && MessagesPigeonUtils.deepEquals(this.quality, other.quality) && MessagesPigeonUtils.deepEquals(this.maxDimension, other.maxDimension) && MessagesPigeonUtils.deepEquals(this.annotations, other.annotations)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.crop)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.flipHorizontal)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.format)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.quality)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.maxDimension)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.annotations)
    return result
  }
  override fun toString(): String {
    return "ImageEditRequest(sourcePath=$sourcePath, outputPath=$outputPath, crop=$crop, rotation=$rotation, flipHorizontal=$flipHorizontal, format=$format, quality=$quality, maxDimension=$maxDimension, annotations=$annotations)"
  }
}

/**
 * One annotation, flattened.
 *
 * Deliberately a single struct with nullable fields rather than a sealed
 * hierarchy: the wire crosses three languages, and a flat record with a kind
 * tag is trivial for each native side to switch on. Dart keeps the sealed,
 * typed version and converts here, so only this one struct is ugly.
 *
 * All geometry is normalized against the *output* frame — after crop and
 * rotation — because that is the frame the author placed it against.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class AnnotationSpec (
  val kind: AnnotationKind,
  /** Clockwise radians. Applies to text and stickers. */
  val rotation: Double,
  val text: String? = null,
  val centerX: Double? = null,
  val centerY: Double? = null,
  /** Cap height as a fraction of the output's height. */
  val heightFraction: Double? = null,
  val colorArgb: Long? = null,
  val backgroundArgb: Long? = null,
  val imagePath: String? = null,
  val rect: NormalizedRect? = null,
  val opacity: Double? = null,
  val strength: Double? = null,
  val shape: BlurShapeSpec? = null,
  /**
   * Stroke points, flattened as x, y, x, y — a flat list survives every
   * codec without a nested type.
   */
  val points: List<Double>? = null,
  /** Stroke width as a fraction of the output's shorter edge. */
  val widthFraction: Double? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): AnnotationSpec {
      val kind = pigeonVar_list[0] as AnnotationKind
      val rotation = pigeonVar_list[1] as Double
      val text = pigeonVar_list[2] as String?
      val centerX = pigeonVar_list[3] as Double?
      val centerY = pigeonVar_list[4] as Double?
      val heightFraction = pigeonVar_list[5] as Double?
      val colorArgb = pigeonVar_list[6] as Long?
      val backgroundArgb = pigeonVar_list[7] as Long?
      val imagePath = pigeonVar_list[8] as String?
      val rect = pigeonVar_list[9] as NormalizedRect?
      val opacity = pigeonVar_list[10] as Double?
      val strength = pigeonVar_list[11] as Double?
      val shape = pigeonVar_list[12] as BlurShapeSpec?
      val points = pigeonVar_list[13] as List<Double>?
      val widthFraction = pigeonVar_list[14] as Double?
      return AnnotationSpec(kind, rotation, text, centerX, centerY, heightFraction, colorArgb, backgroundArgb, imagePath, rect, opacity, strength, shape, points, widthFraction)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      kind,
      rotation,
      text,
      centerX,
      centerY,
      heightFraction,
      colorArgb,
      backgroundArgb,
      imagePath,
      rect,
      opacity,
      strength,
      shape,
      points,
      widthFraction,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as AnnotationSpec
    return MessagesPigeonUtils.deepEquals(this.kind, other.kind) && MessagesPigeonUtils.deepEquals(this.rotation, other.rotation) && MessagesPigeonUtils.deepEquals(this.text, other.text) && MessagesPigeonUtils.deepEquals(this.centerX, other.centerX) && MessagesPigeonUtils.deepEquals(this.centerY, other.centerY) && MessagesPigeonUtils.deepEquals(this.heightFraction, other.heightFraction) && MessagesPigeonUtils.deepEquals(this.colorArgb, other.colorArgb) && MessagesPigeonUtils.deepEquals(this.backgroundArgb, other.backgroundArgb) && MessagesPigeonUtils.deepEquals(this.imagePath, other.imagePath) && MessagesPigeonUtils.deepEquals(this.rect, other.rect) && MessagesPigeonUtils.deepEquals(this.opacity, other.opacity) && MessagesPigeonUtils.deepEquals(this.strength, other.strength) && MessagesPigeonUtils.deepEquals(this.shape, other.shape) && MessagesPigeonUtils.deepEquals(this.points, other.points) && MessagesPigeonUtils.deepEquals(this.widthFraction, other.widthFraction)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.kind)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.text)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.centerX)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.centerY)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.heightFraction)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.colorArgb)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.backgroundArgb)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.imagePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rect)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.opacity)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.strength)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.shape)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.points)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.widthFraction)
    return result
  }
  override fun toString(): String {
    return "AnnotationSpec(kind=$kind, rotation=$rotation, text=$text, centerX=$centerX, centerY=$centerY, heightFraction=$heightFraction, colorArgb=$colorArgb, backgroundArgb=$backgroundArgb, imagePath=$imagePath, rect=$rect, opacity=$opacity, strength=$strength, shape=$shape, points=$points, widthFraction=$widthFraction)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoTrimRequest (
  val sourcePath: String,
  val outputPath: String,
  val startMs: Long,
  val endMs: Long,
  /** Drops the audio track entirely rather than exporting a silent one. */
  val muteAudio: Boolean,
  /** Null crops nothing. */
  val crop: NormalizedRect? = null,
  val rotation: MonoRotation,
  /** Mirrors the *rotated* frame, matching the still path exactly. */
  val flipHorizontal: Boolean,
  /** Burned into every frame, back to front. */
  val annotations: List<AnnotationSpec>
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoTrimRequest {
      val sourcePath = pigeonVar_list[0] as String
      val outputPath = pigeonVar_list[1] as String
      val startMs = pigeonVar_list[2] as Long
      val endMs = pigeonVar_list[3] as Long
      val muteAudio = pigeonVar_list[4] as Boolean
      val crop = pigeonVar_list[5] as NormalizedRect?
      val rotation = pigeonVar_list[6] as MonoRotation
      val flipHorizontal = pigeonVar_list[7] as Boolean
      val annotations = pigeonVar_list[8] as List<AnnotationSpec>
      return VideoTrimRequest(sourcePath, outputPath, startMs, endMs, muteAudio, crop, rotation, flipHorizontal, annotations)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sourcePath,
      outputPath,
      startMs,
      endMs,
      muteAudio,
      crop,
      rotation,
      flipHorizontal,
      annotations,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoTrimRequest
    return MessagesPigeonUtils.deepEquals(this.sourcePath, other.sourcePath) && MessagesPigeonUtils.deepEquals(this.outputPath, other.outputPath) && MessagesPigeonUtils.deepEquals(this.startMs, other.startMs) && MessagesPigeonUtils.deepEquals(this.endMs, other.endMs) && MessagesPigeonUtils.deepEquals(this.muteAudio, other.muteAudio) && MessagesPigeonUtils.deepEquals(this.crop, other.crop) && MessagesPigeonUtils.deepEquals(this.rotation, other.rotation) && MessagesPigeonUtils.deepEquals(this.flipHorizontal, other.flipHorizontal) && MessagesPigeonUtils.deepEquals(this.annotations, other.annotations)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.sourcePath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.outputPath)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.startMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.endMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.muteAudio)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.crop)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.rotation)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.flipHorizontal)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.annotations)
    return result
  }
  override fun toString(): String {
    return "VideoTrimRequest(sourcePath=$sourcePath, outputPath=$outputPath, startMs=$startMs, endMs=$endMs, muteAudio=$muteAudio, crop=$crop, rotation=$rotation, flipHorizontal=$flipHorizontal, annotations=$annotations)"
  }
}

/**
 * What a probe or an export reports back about a file on disk.
 *
 * Generated class from Pigeon that represents data sent in messages.
 */
data class MediaInfo (
  val path: String,
  /**
   * Display dimensions — already rotation-corrected, so a portrait clip
   * recorded on a sensor-landscape device reports portrait here.
   */
  val width: Long,
  val height: Long,
  /** Null for stills. */
  val durationMs: Long? = null,
  val byteSize: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaInfo {
      val path = pigeonVar_list[0] as String
      val width = pigeonVar_list[1] as Long
      val height = pigeonVar_list[2] as Long
      val durationMs = pigeonVar_list[3] as Long?
      val byteSize = pigeonVar_list[4] as Long
      return MediaInfo(path, width, height, durationMs, byteSize)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      path,
      width,
      height,
      durationMs,
      byteSize,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaInfo
    return MessagesPigeonUtils.deepEquals(this.path, other.path) && MessagesPigeonUtils.deepEquals(this.width, other.width) && MessagesPigeonUtils.deepEquals(this.height, other.height) && MessagesPigeonUtils.deepEquals(this.durationMs, other.durationMs) && MessagesPigeonUtils.deepEquals(this.byteSize, other.byteSize)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + MessagesPigeonUtils.deepHash(this.path)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.width)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.height)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.durationMs)
    result = 31 * result + MessagesPigeonUtils.deepHash(this.byteSize)
    return result
  }
  override fun toString(): String {
    return "MediaInfo(path=$path, width=$width, height=$height, durationMs=$durationMs, byteSize=$byteSize)"
  }
}
private open class MessagesPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MonoRotation.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MonoImageFormat.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          AnnotationKind.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          BlurShapeSpec.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          NormalizedRect.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ImageEditRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          AnnotationSpec.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoTrimRequest.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaInfo.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is MonoRotation -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is MonoImageFormat -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is AnnotationKind -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is BlurShapeSpec -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is NormalizedRect -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is ImageEditRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is AnnotationSpec -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is VideoTrimRequest -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is MediaInfo -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface MonolensHostApi {
  /**
   * The app's cache directory, where exports are written.
   *
   * Asked of the platform rather than taken from `path_provider`, so the
   * plugin carries no dependency for one string the native side already knows
   * (`NSTemporaryDirectory()` / `context.cacheDir`). Contents are the OS's to
   * evict — a caller keeping an export must copy it somewhere durable.
   */
  fun cacheDirectory(): String
  /** Reads dimensions, duration and size without decoding the whole file. */
  fun probe(path: String, callback: (Result<MediaInfo>) -> Unit)
  fun editImage(request: ImageEditRequest, callback: (Result<MediaInfo>) -> Unit)
  /**
   * Re-encodes [request]'s range to a new file. [jobId] addresses the export
   * for [cancel] and for progress delivered over [MonolensFlutterApi].
   */
  fun trimVideo(request: VideoTrimRequest, jobId: String, callback: (Result<MediaInfo>) -> Unit)
  /**
   * Requests cancellation of an in-flight [trimVideo]. A cancelled export
   * completes with a `monolens/cancelled` error rather than a result.
   */
  fun cancel(jobId: String)
  /**
   * Decodes frames at [atMs] for the trim filmstrip, each scaled so its
   * longest edge is at most [maxDimension]. Returned as encoded JPEG bytes in
   * the same order as the requested timestamps.
   */
  fun videoThumbnails(path: String, atMs: List<Long>, maxDimension: Long, callback: (Result<List<ByteArray>>) -> Unit)

  companion object {
    /** The codec used by MonolensHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
    /** Sets up an instance of `MonolensHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: MonolensHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.monolens.MonolensHostApi.cacheDirectory$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            val wrapped: List<Any?> = try {
              listOf(api.cacheDirectory())
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.monolens.MonolensHostApi.probe$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            api.probe(pathArg) { result: Result<MediaInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.monolens.MonolensHostApi.editImage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ImageEditRequest
            api.editImage(requestArg) { result: Result<MediaInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.monolens.MonolensHostApi.trimVideo$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VideoTrimRequest
            val jobIdArg = args[1] as String
            api.trimVideo(requestArg, jobIdArg) { result: Result<MediaInfo> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.monolens.MonolensHostApi.cancel$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val jobIdArg = args[0] as String
            val wrapped: List<Any?> = try {
              api.cancel(jobIdArg)
              listOf(null)
            } catch (exception: Throwable) {
              MessagesPigeonUtils.wrapError(exception)
            }
            reply.reply(wrapped)
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.monolens.MonolensHostApi.videoThumbnails$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val pathArg = args[0] as String
            val atMsArg = args[1] as List<Long>
            val maxDimensionArg = args[2] as Long
            api.videoThumbnails(pathArg, atMsArg, maxDimensionArg) { result: Result<List<ByteArray>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(MessagesPigeonUtils.wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(MessagesPigeonUtils.wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class MonolensFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by MonolensFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      MessagesPigeonCodec()
    }
  }
  /** Fractional export progress in 0.0–1.0 for the job identified by [jobId]. */
  fun onProgress(jobIdArg: String, progressArg: Double, callback: (Result<Unit>) -> Unit)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    val channelName = "dev.flutter.pigeon.monolens.MonolensFlutterApi.onProgress$separatedMessageChannelSuffix"
    val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
    channel.send(listOf(jobIdArg, progressArg)) {
      if (it is List<*>) {
        if (it.size > 1) {
          callback(Result.failure(FlutterError(it[0] as String, it[1] as String, it[2] as String?)))
        } else {
          callback(Result.success(Unit))
        }
      } else {
        callback(Result.failure(MessagesPigeonUtils.createConnectionError(channelName)))
      } 
    }
  }
}
