// Autogenerated from Pigeon (v27.3.0), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum MessagesPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Clockwise quarter turns applied after cropping.
enum MonoRotation: Int, CaseIterable {
  case none = 0
  case quarterTurn = 1
  case halfTurn = 2
  case threeQuarterTurns = 3
}

/// How a still is re-encoded on export.
enum MonoImageFormat: Int, CaseIterable {
  case jpeg = 0
  case png = 1
}

/// Which kind of overlay an [AnnotationSpec] describes.
enum AnnotationKind: Int, CaseIterable {
  case text = 0
  case sticker = 1
  case blur = 2
  case stroke = 3
}

enum BlurShapeSpec: Int, CaseIterable {
  case rectangle = 0
  case oval = 1
}

/// A crop as fractions of the frame, 0–1.
///
/// Normalized all the way to the platform rather than resolved to pixels in
/// Dart. That removes a probe round trip per edit — the native side is opening
/// the file anyway and already knows its dimensions — and it removes the chance
/// of the two sides disagreeing about what those dimensions are.
///
/// Generated class from Pigeon that represents data sent in messages.
struct NormalizedRect: Hashable, CustomStringConvertible {
  var left: Double
  var top: Double
  var width: Double
  var height: Double


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> NormalizedRect? {
    let left = pigeonVar_list[0] as! Double
    let top = pigeonVar_list[1] as! Double
    let width = pigeonVar_list[2] as! Double
    let height = pigeonVar_list[3] as! Double

    return NormalizedRect(
      left: left,
      top: top,
      width: width,
      height: height
    )
  }
  func toList() -> [Any?] {
    return [
      left,
      top,
      width,
      height,
    ]
  }
  static func == (lhs: NormalizedRect, rhs: NormalizedRect) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.left, rhs.left) && MessagesPigeonInternal.deepEquals(lhs.top, rhs.top) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("NormalizedRect")
    MessagesPigeonInternal.deepHash(value: left, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: top, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
  }

  public var description: String {
    return "NormalizedRect(left: \(String(describing: left)), top: \(String(describing: top)), width: \(String(describing: width)), height: \(String(describing: height)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ImageEditRequest: Hashable, CustomStringConvertible {
  var sourcePath: String
  var outputPath: String
  /// Null crops nothing — the full frame is re-encoded.
  var crop: NormalizedRect? = nil
  var rotation: MonoRotation
  var flipHorizontal: Bool
  var format: MonoImageFormat
  /// 1–100. Ignored for [MonoImageFormat.png].
  var quality: Int64
  /// Downscales so the longest edge is at most this many pixels. Null keeps the
  /// cropped size. Applied after crop and rotation.
  var maxDimension: Int64? = nil
  /// Painted over the result, back to front, after every transform.
  var annotations: [AnnotationSpec]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ImageEditRequest? {
    let sourcePath = pigeonVar_list[0] as! String
    let outputPath = pigeonVar_list[1] as! String
    let crop: NormalizedRect? = nilOrValue(pigeonVar_list[2])
    let rotation = pigeonVar_list[3] as! MonoRotation
    let flipHorizontal = pigeonVar_list[4] as! Bool
    let format = pigeonVar_list[5] as! MonoImageFormat
    let quality = pigeonVar_list[6] as! Int64
    let maxDimension: Int64? = nilOrValue(pigeonVar_list[7])
    let annotations = pigeonVar_list[8] as! [AnnotationSpec]

    return ImageEditRequest(
      sourcePath: sourcePath,
      outputPath: outputPath,
      crop: crop,
      rotation: rotation,
      flipHorizontal: flipHorizontal,
      format: format,
      quality: quality,
      maxDimension: maxDimension,
      annotations: annotations
    )
  }
  func toList() -> [Any?] {
    return [
      sourcePath,
      outputPath,
      crop,
      rotation,
      flipHorizontal,
      format,
      quality,
      maxDimension,
      annotations,
    ]
  }
  static func == (lhs: ImageEditRequest, rhs: ImageEditRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.crop, rhs.crop) && MessagesPigeonInternal.deepEquals(lhs.rotation, rhs.rotation) && MessagesPigeonInternal.deepEquals(lhs.flipHorizontal, rhs.flipHorizontal) && MessagesPigeonInternal.deepEquals(lhs.format, rhs.format) && MessagesPigeonInternal.deepEquals(lhs.quality, rhs.quality) && MessagesPigeonInternal.deepEquals(lhs.maxDimension, rhs.maxDimension) && MessagesPigeonInternal.deepEquals(lhs.annotations, rhs.annotations)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ImageEditRequest")
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: crop, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: flipHorizontal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: format, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: quality, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: maxDimension, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: annotations, hasher: &hasher)
  }

  public var description: String {
    return "ImageEditRequest(sourcePath: \(String(describing: sourcePath)), outputPath: \(String(describing: outputPath)), crop: \(String(describing: crop)), rotation: \(String(describing: rotation)), flipHorizontal: \(String(describing: flipHorizontal)), format: \(String(describing: format)), quality: \(String(describing: quality)), maxDimension: \(String(describing: maxDimension)), annotations: \(String(describing: annotations)))"
  }
}

/// One annotation, flattened.
///
/// Deliberately a single struct with nullable fields rather than a sealed
/// hierarchy: the wire crosses three languages, and a flat record with a kind
/// tag is trivial for each native side to switch on. Dart keeps the sealed,
/// typed version and converts here, so only this one struct is ugly.
///
/// All geometry is normalized against the *output* frame — after crop and
/// rotation — because that is the frame the author placed it against.
///
/// Generated class from Pigeon that represents data sent in messages.
struct AnnotationSpec: Hashable, CustomStringConvertible {
  var kind: AnnotationKind
  /// Clockwise radians. Applies to text and stickers.
  var rotation: Double
  var text: String? = nil
  var centerX: Double? = nil
  var centerY: Double? = nil
  /// Cap height as a fraction of the output's height.
  var heightFraction: Double? = nil
  var colorArgb: Int64? = nil
  var backgroundArgb: Int64? = nil
  var imagePath: String? = nil
  var rect: NormalizedRect? = nil
  var opacity: Double? = nil
  var strength: Double? = nil
  var shape: BlurShapeSpec? = nil
  /// Stroke points, flattened as x, y, x, y — a flat list survives every
  /// codec without a nested type.
  var points: [Double]? = nil
  /// Stroke width as a fraction of the output's shorter edge.
  var widthFraction: Double? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> AnnotationSpec? {
    let kind = pigeonVar_list[0] as! AnnotationKind
    let rotation = pigeonVar_list[1] as! Double
    let text: String? = nilOrValue(pigeonVar_list[2])
    let centerX: Double? = nilOrValue(pigeonVar_list[3])
    let centerY: Double? = nilOrValue(pigeonVar_list[4])
    let heightFraction: Double? = nilOrValue(pigeonVar_list[5])
    let colorArgb: Int64? = nilOrValue(pigeonVar_list[6])
    let backgroundArgb: Int64? = nilOrValue(pigeonVar_list[7])
    let imagePath: String? = nilOrValue(pigeonVar_list[8])
    let rect: NormalizedRect? = nilOrValue(pigeonVar_list[9])
    let opacity: Double? = nilOrValue(pigeonVar_list[10])
    let strength: Double? = nilOrValue(pigeonVar_list[11])
    let shape: BlurShapeSpec? = nilOrValue(pigeonVar_list[12])
    let points: [Double]? = nilOrValue(pigeonVar_list[13])
    let widthFraction: Double? = nilOrValue(pigeonVar_list[14])

    return AnnotationSpec(
      kind: kind,
      rotation: rotation,
      text: text,
      centerX: centerX,
      centerY: centerY,
      heightFraction: heightFraction,
      colorArgb: colorArgb,
      backgroundArgb: backgroundArgb,
      imagePath: imagePath,
      rect: rect,
      opacity: opacity,
      strength: strength,
      shape: shape,
      points: points,
      widthFraction: widthFraction
    )
  }
  func toList() -> [Any?] {
    return [
      kind,
      rotation,
      text,
      centerX,
      centerY,
      heightFraction,
      colorArgb,
      backgroundArgb,
      imagePath,
      rect,
      opacity,
      strength,
      shape,
      points,
      widthFraction,
    ]
  }
  static func == (lhs: AnnotationSpec, rhs: AnnotationSpec) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.kind, rhs.kind) && MessagesPigeonInternal.deepEquals(lhs.rotation, rhs.rotation) && MessagesPigeonInternal.deepEquals(lhs.text, rhs.text) && MessagesPigeonInternal.deepEquals(lhs.centerX, rhs.centerX) && MessagesPigeonInternal.deepEquals(lhs.centerY, rhs.centerY) && MessagesPigeonInternal.deepEquals(lhs.heightFraction, rhs.heightFraction) && MessagesPigeonInternal.deepEquals(lhs.colorArgb, rhs.colorArgb) && MessagesPigeonInternal.deepEquals(lhs.backgroundArgb, rhs.backgroundArgb) && MessagesPigeonInternal.deepEquals(lhs.imagePath, rhs.imagePath) && MessagesPigeonInternal.deepEquals(lhs.rect, rhs.rect) && MessagesPigeonInternal.deepEquals(lhs.opacity, rhs.opacity) && MessagesPigeonInternal.deepEquals(lhs.strength, rhs.strength) && MessagesPigeonInternal.deepEquals(lhs.shape, rhs.shape) && MessagesPigeonInternal.deepEquals(lhs.points, rhs.points) && MessagesPigeonInternal.deepEquals(lhs.widthFraction, rhs.widthFraction)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("AnnotationSpec")
    MessagesPigeonInternal.deepHash(value: kind, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: text, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: centerX, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: centerY, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: heightFraction, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: colorArgb, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: backgroundArgb, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: imagePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rect, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: opacity, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: strength, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: shape, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: points, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: widthFraction, hasher: &hasher)
  }

  public var description: String {
    return "AnnotationSpec(kind: \(String(describing: kind)), rotation: \(String(describing: rotation)), text: \(String(describing: text)), centerX: \(String(describing: centerX)), centerY: \(String(describing: centerY)), heightFraction: \(String(describing: heightFraction)), colorArgb: \(String(describing: colorArgb)), backgroundArgb: \(String(describing: backgroundArgb)), imagePath: \(String(describing: imagePath)), rect: \(String(describing: rect)), opacity: \(String(describing: opacity)), strength: \(String(describing: strength)), shape: \(String(describing: shape)), points: \(String(describing: points)), widthFraction: \(String(describing: widthFraction)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoTrimRequest: Hashable, CustomStringConvertible {
  var sourcePath: String
  var outputPath: String
  var startMs: Int64
  var endMs: Int64
  /// Drops the audio track entirely rather than exporting a silent one.
  var muteAudio: Bool
  /// Null crops nothing.
  var crop: NormalizedRect? = nil
  var rotation: MonoRotation
  /// Mirrors the *rotated* frame, matching the still path exactly.
  var flipHorizontal: Bool
  /// Burned into every frame, back to front.
  var annotations: [AnnotationSpec]


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoTrimRequest? {
    let sourcePath = pigeonVar_list[0] as! String
    let outputPath = pigeonVar_list[1] as! String
    let startMs = pigeonVar_list[2] as! Int64
    let endMs = pigeonVar_list[3] as! Int64
    let muteAudio = pigeonVar_list[4] as! Bool
    let crop: NormalizedRect? = nilOrValue(pigeonVar_list[5])
    let rotation = pigeonVar_list[6] as! MonoRotation
    let flipHorizontal = pigeonVar_list[7] as! Bool
    let annotations = pigeonVar_list[8] as! [AnnotationSpec]

    return VideoTrimRequest(
      sourcePath: sourcePath,
      outputPath: outputPath,
      startMs: startMs,
      endMs: endMs,
      muteAudio: muteAudio,
      crop: crop,
      rotation: rotation,
      flipHorizontal: flipHorizontal,
      annotations: annotations
    )
  }
  func toList() -> [Any?] {
    return [
      sourcePath,
      outputPath,
      startMs,
      endMs,
      muteAudio,
      crop,
      rotation,
      flipHorizontal,
      annotations,
    ]
  }
  static func == (lhs: VideoTrimRequest, rhs: VideoTrimRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.sourcePath, rhs.sourcePath) && MessagesPigeonInternal.deepEquals(lhs.outputPath, rhs.outputPath) && MessagesPigeonInternal.deepEquals(lhs.startMs, rhs.startMs) && MessagesPigeonInternal.deepEquals(lhs.endMs, rhs.endMs) && MessagesPigeonInternal.deepEquals(lhs.muteAudio, rhs.muteAudio) && MessagesPigeonInternal.deepEquals(lhs.crop, rhs.crop) && MessagesPigeonInternal.deepEquals(lhs.rotation, rhs.rotation) && MessagesPigeonInternal.deepEquals(lhs.flipHorizontal, rhs.flipHorizontal) && MessagesPigeonInternal.deepEquals(lhs.annotations, rhs.annotations)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoTrimRequest")
    MessagesPigeonInternal.deepHash(value: sourcePath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: outputPath, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: startMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: endMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: muteAudio, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: crop, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: rotation, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: flipHorizontal, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: annotations, hasher: &hasher)
  }

  public var description: String {
    return "VideoTrimRequest(sourcePath: \(String(describing: sourcePath)), outputPath: \(String(describing: outputPath)), startMs: \(String(describing: startMs)), endMs: \(String(describing: endMs)), muteAudio: \(String(describing: muteAudio)), crop: \(String(describing: crop)), rotation: \(String(describing: rotation)), flipHorizontal: \(String(describing: flipHorizontal)), annotations: \(String(describing: annotations)))"
  }
}

/// What a probe or an export reports back about a file on disk.
///
/// Generated class from Pigeon that represents data sent in messages.
struct MediaInfo: Hashable, CustomStringConvertible {
  var path: String
  /// Display dimensions — already rotation-corrected, so a portrait clip
  /// recorded on a sensor-landscape device reports portrait here.
  var width: Int64
  var height: Int64
  /// Null for stills.
  var durationMs: Int64? = nil
  var byteSize: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaInfo? {
    let path = pigeonVar_list[0] as! String
    let width = pigeonVar_list[1] as! Int64
    let height = pigeonVar_list[2] as! Int64
    let durationMs: Int64? = nilOrValue(pigeonVar_list[3])
    let byteSize = pigeonVar_list[4] as! Int64

    return MediaInfo(
      path: path,
      width: width,
      height: height,
      durationMs: durationMs,
      byteSize: byteSize
    )
  }
  func toList() -> [Any?] {
    return [
      path,
      width,
      height,
      durationMs,
      byteSize,
    ]
  }
  static func == (lhs: MediaInfo, rhs: MediaInfo) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return MessagesPigeonInternal.deepEquals(lhs.path, rhs.path) && MessagesPigeonInternal.deepEquals(lhs.width, rhs.width) && MessagesPigeonInternal.deepEquals(lhs.height, rhs.height) && MessagesPigeonInternal.deepEquals(lhs.durationMs, rhs.durationMs) && MessagesPigeonInternal.deepEquals(lhs.byteSize, rhs.byteSize)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaInfo")
    MessagesPigeonInternal.deepHash(value: path, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: width, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: height, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: durationMs, hasher: &hasher)
    MessagesPigeonInternal.deepHash(value: byteSize, hasher: &hasher)
  }

  public var description: String {
    return "MediaInfo(path: \(String(describing: path)), width: \(String(describing: width)), height: \(String(describing: height)), durationMs: \(String(describing: durationMs)), byteSize: \(String(describing: byteSize)))"
  }
}

private class MessagesPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MonoRotation(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MonoImageFormat(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return AnnotationKind(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return BlurShapeSpec(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      return NormalizedRect.fromList(self.readValue() as! [Any?])
    case 134:
      return ImageEditRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return AnnotationSpec.fromList(self.readValue() as! [Any?])
    case 136:
      return VideoTrimRequest.fromList(self.readValue() as! [Any?])
    case 137:
      return MediaInfo.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class MessagesPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? MonoRotation {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? MonoImageFormat {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? AnnotationKind {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? BlurShapeSpec {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? NormalizedRect {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? ImageEditRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? AnnotationSpec {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? VideoTrimRequest {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? MediaInfo {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class MessagesPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return MessagesPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return MessagesPigeonCodecWriter(data: data)
  }
}

class MessagesPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = MessagesPigeonCodec(readerWriter: MessagesPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol MonolensHostApi {
  /// The app's cache directory, where exports are written.
  ///
  /// Asked of the platform rather than taken from `path_provider`, so the
  /// plugin carries no dependency for one string the native side already knows
  /// (`NSTemporaryDirectory()` / `context.cacheDir`). Contents are the OS's to
  /// evict — a caller keeping an export must copy it somewhere durable.
  func cacheDirectory() throws -> String
  /// Reads dimensions, duration and size without decoding the whole file.
  func probe(path: String, completion: @escaping (Result<MediaInfo, Error>) -> Void)
  func editImage(request: ImageEditRequest, completion: @escaping (Result<MediaInfo, Error>) -> Void)
  /// Re-encodes [request]'s range to a new file. [jobId] addresses the export
  /// for [cancel] and for progress delivered over [MonolensFlutterApi].
  func trimVideo(request: VideoTrimRequest, jobId: String, completion: @escaping (Result<MediaInfo, Error>) -> Void)
  /// Requests cancellation of an in-flight [trimVideo]. A cancelled export
  /// completes with a `monolens/cancelled` error rather than a result.
  func cancel(jobId: String) throws
  /// Decodes frames at [atMs] for the trim filmstrip, each scaled so its
  /// longest edge is at most [maxDimension]. Returned as encoded JPEG bytes in
  /// the same order as the requested timestamps.
  func videoThumbnails(path: String, atMs: [Int64], maxDimension: Int64, completion: @escaping (Result<[FlutterStandardTypedData], Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class MonolensHostApiSetup {
  static var codec: FlutterStandardMessageCodec { MessagesPigeonCodec.shared }
  /// Sets up an instance of `MonolensHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: MonolensHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    /// The app's cache directory, where exports are written.
    ///
    /// Asked of the platform rather than taken from `path_provider`, so the
    /// plugin carries no dependency for one string the native side already knows
    /// (`NSTemporaryDirectory()` / `context.cacheDir`). Contents are the OS's to
    /// evict — a caller keeping an export must copy it somewhere durable.
    let cacheDirectoryChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.monolens.MonolensHostApi.cacheDirectory\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cacheDirectoryChannel.setMessageHandler { _, reply in
        do {
          let result = try api.cacheDirectory()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cacheDirectoryChannel.setMessageHandler(nil)
    }
    /// Reads dimensions, duration and size without decoding the whole file.
    let probeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.monolens.MonolensHostApi.probe\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      probeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        api.probe(path: pathArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      probeChannel.setMessageHandler(nil)
    }
    let editImageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.monolens.MonolensHostApi.editImage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      editImageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ImageEditRequest
        api.editImage(request: requestArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      editImageChannel.setMessageHandler(nil)
    }
    /// Re-encodes [request]'s range to a new file. [jobId] addresses the export
    /// for [cancel] and for progress delivered over [MonolensFlutterApi].
    let trimVideoChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.monolens.MonolensHostApi.trimVideo\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      trimVideoChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VideoTrimRequest
        let jobIdArg = args[1] as! String
        api.trimVideo(request: requestArg, jobId: jobIdArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      trimVideoChannel.setMessageHandler(nil)
    }
    /// Requests cancellation of an in-flight [trimVideo]. A cancelled export
    /// completes with a `monolens/cancelled` error rather than a result.
    let cancelChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.monolens.MonolensHostApi.cancel\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      cancelChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let jobIdArg = args[0] as! String
        do {
          try api.cancel(jobId: jobIdArg)
          reply(wrapResult(nil))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      cancelChannel.setMessageHandler(nil)
    }
    /// Decodes frames at [atMs] for the trim filmstrip, each scaled so its
    /// longest edge is at most [maxDimension]. Returned as encoded JPEG bytes in
    /// the same order as the requested timestamps.
    let videoThumbnailsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.monolens.MonolensHostApi.videoThumbnails\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      videoThumbnailsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let pathArg = args[0] as! String
        let atMsArg = args[1] as! [Int64]
        let maxDimensionArg = args[2] as! Int64
        api.videoThumbnails(path: pathArg, atMs: atMsArg, maxDimension: maxDimensionArg) { result in
          switch result {
          case .success(let res):
            reply(wrapResult(res))
          case .failure(let error):
            reply(wrapError(error))
          }
        }
      }
    } else {
      videoThumbnailsChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol MonolensFlutterApiProtocol {
  /// Fractional export progress in 0.0–1.0 for the job identified by [jobId].
  func onProgress(jobId jobIdArg: String, progress progressArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void)
}
class MonolensFlutterApi: MonolensFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: MessagesPigeonCodec {
    return MessagesPigeonCodec.shared
  }
  /// Fractional export progress in 0.0–1.0 for the job identified by [jobId].
  func onProgress(jobId jobIdArg: String, progress progressArg: Double, completion: @escaping (Result<Void, PigeonError>) -> Void) {
    let channelName: String = "dev.flutter.pigeon.monolens.MonolensFlutterApi.onProgress\(messageChannelSuffix)"
    let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([jobIdArg, progressArg] as [Any?]) { response in
      guard let listResponse = response as? [Any?] else {
        completion(.failure(createConnectionError(withChannelName: channelName)))
        return
      }
      if listResponse.count > 1 {
        let code: String = listResponse[0] as! String
        let message: String? = nilOrValue(listResponse[1])
        let details: String? = nilOrValue(listResponse[2])
        completion(.failure(PigeonError(code: code, message: message, details: details)))
      } else {
        completion(.success(()))
      }
    }
  }
}
